"""
WARNING: File generated with the help of AI provided with firmware SDK header file
Based on sl_status.h
"""

from __future__ import annotations

# Keep the map at module scope so it isn't rebuilt on every call.
_STATUS_MAP: dict[int, str] = {
    # ---------------------------------------------------------------------
    # Space Defines (also SL_STATUS_* macros in the header)
    # ---------------------------------------------------------------------
    0xFF00: "SL_STATUS_SPACE_MASK",
    0x0000: "SL_STATUS_GENERIC_SPACE",
    0x0100: "SL_STATUS_PLATFORM_1_SPACE",
    0x0200: "SL_STATUS_PLATFORM_2_SPACE",
    0x0300: "SL_STATUS_HARDWARE_SPACE",
    0x0400: "SL_STATUS_BLUETOOTH_SPACE",
    0x0500: "SL_STATUS_BLUETOOTH_MESH_SPACE",
    0x0600: "SL_STATUS_CAN_CANOPEN_SPACE",
    0x0700: "SL_STATUS_CONNECT_SPACE",
    0x0800: "SL_STATUS_NET_SUITE_SPACE",
    0x0900: "SL_STATUS_THREAD_SPACE",
    0x0A00: "SL_STATUS_USB_SPACE",
    0x0B00: "SL_STATUS_WIFI_SPACE",
    0x0C00: "SL_STATUS_ZIGBEE_SPACE",
    0x0D00: "SL_STATUS_Z_WAVE_SPACE",
    0x0E00: "SL_STATUS_GECKO_OS_1_SPACE",
    0x0F00: "SL_STATUS_GECKO_OS_2_SPACE",
    0x1000: "SL_STATUS_BLUETOOTH_CTRL_SPACE",
    0x1100: "SL_STATUS_BLUETOOTH_ATT_SPACE",
    0x1200: "SL_STATUS_BLUETOOTH_SMP_SPACE",
    0x1300: "SL_STATUS_BLUETOOTH_MESH_FOUNDATION_SPACE",
    0x1400: "SL_STATUS_WISUN_SPACE",
    0x1500: "SL_STATUS_COMPUTE_SPACE",

    # ---------------------------------------------------------------------
    # Generic Errors
    # ---------------------------------------------------------------------
    0x0000: "SL_STATUS_OK",
    0x0001: "SL_STATUS_FAIL",

    # ---------------------------------------------------------------------
    # State Errors
    # ---------------------------------------------------------------------
    0x0002: "SL_STATUS_INVALID_STATE",
    0x0003: "SL_STATUS_NOT_READY",
    0x0004: "SL_STATUS_BUSY",
    0x0005: "SL_STATUS_IN_PROGRESS",
    0x0006: "SL_STATUS_ABORT",
    0x0007: "SL_STATUS_TIMEOUT",
    0x0008: "SL_STATUS_PERMISSION",
    0x0009: "SL_STATUS_WOULD_BLOCK",
    0x000A: "SL_STATUS_IDLE",
    0x000B: "SL_STATUS_IS_WAITING",
    0x000C: "SL_STATUS_NONE_WAITING",
    0x000D: "SL_STATUS_SUSPENDED",
    0x000E: "SL_STATUS_NOT_AVAILABLE",
    0x000F: "SL_STATUS_NOT_SUPPORTED",
    0x0010: "SL_STATUS_INITIALIZATION",
    0x0011: "SL_STATUS_NOT_INITIALIZED",
    0x0012: "SL_STATUS_ALREADY_INITIALIZED",
    0x0013: "SL_STATUS_DELETED",
    0x0014: "SL_STATUS_ISR",
    0x0015: "SL_STATUS_NETWORK_UP",
    0x0016: "SL_STATUS_NETWORK_DOWN",
    0x0017: "SL_STATUS_NOT_JOINED",
    0x0018: "SL_STATUS_NO_BEACONS",

    # ---------------------------------------------------------------------
    # Allocation / ownership Errors
    # ---------------------------------------------------------------------
    0x0019: "SL_STATUS_ALLOCATION_FAILED",
    0x001A: "SL_STATUS_NO_MORE_RESOURCE",
    0x001B: "SL_STATUS_EMPTY",
    0x001C: "SL_STATUS_FULL",
    0x001D: "SL_STATUS_WOULD_OVERFLOW",
    0x001E: "SL_STATUS_HAS_OVERFLOWED",
    0x001F: "SL_STATUS_OWNERSHIP",
    0x0020: "SL_STATUS_IS_OWNER",

    # ---------------------------------------------------------------------
    # Invalid Parameters Errors
    # ---------------------------------------------------------------------
    0x0021: "SL_STATUS_INVALID_PARAMETER",
    0x0022: "SL_STATUS_NULL_POINTER",
    0x0023: "SL_STATUS_INVALID_CONFIGURATION",
    0x0024: "SL_STATUS_INVALID_MODE",
    0x0025: "SL_STATUS_INVALID_HANDLE",
    0x0026: "SL_STATUS_INVALID_TYPE",
    0x0027: "SL_STATUS_INVALID_INDEX",
    0x0028: "SL_STATUS_INVALID_RANGE",
    0x0029: "SL_STATUS_INVALID_KEY",
    0x002A: "SL_STATUS_INVALID_CREDENTIALS",
    0x002B: "SL_STATUS_INVALID_COUNT",
    0x002C: "SL_STATUS_INVALID_SIGNATURE",
    0x002D: "SL_STATUS_NOT_FOUND",
    0x002E: "SL_STATUS_ALREADY_EXISTS",

    # ---------------------------------------------------------------------
    # IO / Communication Errors
    # ---------------------------------------------------------------------
    0x002F: "SL_STATUS_IO",
    0x0030: "SL_STATUS_IO_TIMEOUT",
    0x0031: "SL_STATUS_TRANSMIT",
    0x0032: "SL_STATUS_TRANSMIT_UNDERFLOW",
    0x0033: "SL_STATUS_TRANSMIT_INCOMPLETE",
    0x0034: "SL_STATUS_TRANSMIT_BUSY",
    0x0035: "SL_STATUS_RECEIVE",
    0x0036: "SL_STATUS_OBJECT_READ",
    0x0037: "SL_STATUS_OBJECT_WRITE",
    0x0038: "SL_STATUS_MESSAGE_TOO_LONG",

    # ---------------------------------------------------------------------
    # EEPROM / Flash Errors
    # ---------------------------------------------------------------------
    0x0039: "SL_STATUS_EEPROM_MFG_VERSION_MISMATCH",
    0x003A: "SL_STATUS_EEPROM_STACK_VERSION_MISMATCH",
    0x003B: "SL_STATUS_FLASH_WRITE_INHIBITED",
    0x003C: "SL_STATUS_FLASH_VERIFY_FAILED",
    0x003D: "SL_STATUS_FLASH_PROGRAM_FAILED",
    0x003E: "SL_STATUS_FLASH_ERASE_FAILED",

    # ---------------------------------------------------------------------
    # MAC / CLI Storage / Security / Command / Misc / Scan
    # ---------------------------------------------------------------------
    0x003F: "SL_STATUS_MAC_NO_DATA",
    0x0040: "SL_STATUS_MAC_NO_ACK_RECEIVED",
    0x0041: "SL_STATUS_MAC_INDIRECT_TIMEOUT",
    0x0042: "SL_STATUS_MAC_UNKNOWN_HEADER_TYPE",
    0x0043: "SL_STATUS_MAC_ACK_HEADER_TYPE",
    0x0044: "SL_STATUS_MAC_COMMAND_TRANSMIT_FAILURE",
    0x0045: "SL_STATUS_CLI_STORAGE_NVM_OPEN_ERROR",
    0x0046: "SL_STATUS_SECURITY_IMAGE_CHECKSUM_ERROR",
    0x0047: "SL_STATUS_SECURITY_DECRYPT_ERROR",
    0x0048: "SL_STATUS_COMMAND_IS_INVALID",
    0x0049: "SL_STATUS_COMMAND_TOO_LONG",
    0x004A: "SL_STATUS_COMMAND_INCOMPLETE",
    0x004B: "SL_STATUS_BUS_ERROR",
    0x004C: "SL_STATUS_CCA_FAILURE",
    0x004D: "SL_STATUS_MAC_SCANNING",
    0x004E: "SL_STATUS_MAC_INCORRECT_SCAN_TYPE",
    0x004F: "SL_STATUS_INVALID_CHANNEL_MASK",
    0x0050: "SL_STATUS_BAD_SCAN_DURATION",

    # ---------------------------------------------------------------------
    # Bluetooth status codes
    # ---------------------------------------------------------------------
    0x0402: "SL_STATUS_BT_OUT_OF_BONDS",
    0x0403: "SL_STATUS_BT_UNSPECIFIED",
    0x0404: "SL_STATUS_BT_HARDWARE",
    0x0406: "SL_STATUS_BT_NO_BONDING",
    0x0407: "SL_STATUS_BT_CRYPTO",
    0x0408: "SL_STATUS_BT_DATA_CORRUPTED",
    0x040A: "SL_STATUS_BT_INVALID_SYNC_HANDLE",
    0x040B: "SL_STATUS_BT_INVALID_MODULE_ACTION",
    0x040C: "SL_STATUS_BT_RADIO",
    0x040D: "SL_STATUS_BT_L2CAP_REMOTE_DISCONNECTED",
    0x040E: "SL_STATUS_BT_L2CAP_LOCAL_DISCONNECTED",
    0x040F: "SL_STATUS_BT_L2CAP_CID_NOT_EXIST",
    0x0410: "SL_STATUS_BT_L2CAP_LE_DISCONNECTED",
    0x0412: "SL_STATUS_BT_L2CAP_FLOW_CONTROL_VIOLATED",
    0x0413: "SL_STATUS_BT_L2CAP_FLOW_CONTROL_CREDIT_OVERFLOWED",
    0x0414: "SL_STATUS_BT_L2CAP_NO_FLOW_CONTROL_CREDIT",
    0x0415: "SL_STATUS_BT_L2CAP_CONNECTION_REQUEST_TIMEOUT",
    0x0416: "SL_STATUS_BT_L2CAP_INVALID_CID",
    0x0417: "SL_STATUS_BT_L2CAP_WRONG_STATE",
    0x041B: "SL_STATUS_BT_PS_STORE_FULL",
    0x041C: "SL_STATUS_BT_PS_KEY_NOT_FOUND",
    0x041D: "SL_STATUS_BT_APPLICATION_MISMATCHED_OR_INSUFFICIENT_SECURITY",
    0x041E: "SL_STATUS_BT_APPLICATION_ENCRYPTION_DECRYPTION_ERROR",

    # ---------------------------------------------------------------------
    # Bluetooth Controller status codes
    # ---------------------------------------------------------------------
    0x1002: "SL_STATUS_BT_CTRL_UNKNOWN_CONNECTION_IDENTIFIER",
    0x1005: "SL_STATUS_BT_CTRL_AUTHENTICATION_FAILURE",
    0x1006: "SL_STATUS_BT_CTRL_PIN_OR_KEY_MISSING",
    0x1007: "SL_STATUS_BT_CTRL_MEMORY_CAPACITY_EXCEEDED",
    0x1008: "SL_STATUS_BT_CTRL_CONNECTION_TIMEOUT",
    0x1009: "SL_STATUS_BT_CTRL_CONNECTION_LIMIT_EXCEEDED",
    0x100A: "SL_STATUS_BT_CTRL_SYNCHRONOUS_CONNECTION_LIMIT_EXCEEDED",
    0x100B: "SL_STATUS_BT_CTRL_ACL_CONNECTION_ALREADY_EXISTS",
    0x100C: "SL_STATUS_BT_CTRL_COMMAND_DISALLOWED",
    0x100D: "SL_STATUS_BT_CTRL_CONNECTION_REJECTED_DUE_TO_LIMITED_RESOURCES",
    0x100E: "SL_STATUS_BT_CTRL_CONNECTION_REJECTED_DUE_TO_SECURITY_REASONS",
    0x100F: "SL_STATUS_BT_CTRL_CONNECTION_REJECTED_DUE_TO_UNACCEPTABLE_BD_ADDR",
    0x1010: "SL_STATUS_BT_CTRL_CONNECTION_ACCEPT_TIMEOUT_EXCEEDED",
    0x1011: "SL_STATUS_BT_CTRL_UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE",
    0x1012: "SL_STATUS_BT_CTRL_INVALID_COMMAND_PARAMETERS",
    0x1013: "SL_STATUS_BT_CTRL_REMOTE_USER_TERMINATED",
    0x1014: "SL_STATUS_BT_CTRL_REMOTE_DEVICE_TERMINATED_CONNECTION_DUE_TO_LOW_RESOURCES",
    0x1015: "SL_STATUS_BT_CTRL_REMOTE_POWERING_OFF",
    0x1016: "SL_STATUS_BT_CTRL_CONNECTION_TERMINATED_BY_LOCAL_HOST",
    0x1017: "SL_STATUS_BT_CTRL_REPEATED_ATTEMPTS",
    0x1018: "SL_STATUS_BT_CTRL_PAIRING_NOT_ALLOWED",
    0x101A: "SL_STATUS_BT_CTRL_UNSUPPORTED_REMOTE_FEATURE",
    0x101F: "SL_STATUS_BT_CTRL_UNSPECIFIED_ERROR",
    0x1022: "SL_STATUS_BT_CTRL_LL_RESPONSE_TIMEOUT",
    0x1023: "SL_STATUS_BT_CTRL_LL_PROCEDURE_COLLISION",
    0x1025: "SL_STATUS_BT_CTRL_ENCRYPTION_MODE_NOT_ACCEPTABLE",
    0x1026: "SL_STATUS_BT_CTRL_LINK_KEY_CANNOT_BE_CHANGED",
    0x1028: "SL_STATUS_BT_CTRL_INSTANT_PASSED",
    0x1029: "SL_STATUS_BT_CTRL_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED",
    0x102A: "SL_STATUS_BT_CTRL_DIFFERENT_TRANSACTION_COLLISION",
    0x102E: "SL_STATUS_BT_CTRL_CHANNEL_ASSESSMENT_NOT_SUPPORTED",
    0x102F: "SL_STATUS_BT_CTRL_INSUFFICIENT_SECURITY",
    0x1030: "SL_STATUS_BT_CTRL_PARAMETER_OUT_OF_MANDATORY_RANGE",
    0x1037: "SL_STATUS_BT_CTRL_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST",
    0x1038: "SL_STATUS_BT_CTRL_HOST_BUSY_PAIRING",
    0x1039: "SL_STATUS_BT_CTRL_CONNECTION_REJECTED_DUE_TO_NO_SUITABLE_CHANNEL_FOUND",
    0x103A: "SL_STATUS_BT_CTRL_CONTROLLER_BUSY",
    0x103B: "SL_STATUS_BT_CTRL_UNACCEPTABLE_CONNECTION_INTERVAL",
    0x103C: "SL_STATUS_BT_CTRL_ADVERTISING_TIMEOUT",
    0x103D: "SL_STATUS_BT_CTRL_CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE",
    0x103E: "SL_STATUS_BT_CTRL_CONNECTION_FAILED_TO_BE_ESTABLISHED",
    0x103F: "SL_STATUS_BT_CTRL_MAC_CONNECTION_FAILED",
    0x1040: "SL_STATUS_BT_CTRL_COARSE_CLOCK_ADJUSTMENT_REJECTED_BUT_WILL_TRY_TO_ADJUST_USING_CLOCK_DRAGGING",
    0x1042: "SL_STATUS_BT_CTRL_UNKNOWN_ADVERTISING_IDENTIFIER",
    0x1043: "SL_STATUS_BT_CTRL_LIMIT_REACHED",
    0x1044: "SL_STATUS_BT_CTRL_OPERATION_CANCELLED_BY_HOST",
    0x1045: "SL_STATUS_BT_CTRL_PACKET_TOO_LONG",
    0x1046: "SL_STATUS_BT_CTRL_TOO_LATE",
    0x1047: "SL_STATUS_BT_CTRL_TOO_EARLY",

    # ---------------------------------------------------------------------
    # Bluetooth ATT (Attribute) status codes
    # ---------------------------------------------------------------------
    0x1101: "SL_STATUS_BT_ATT_INVALID_HANDLE",
    0x1102: "SL_STATUS_BT_ATT_READ_NOT_PERMITTED",
    0x1103: "SL_STATUS_BT_ATT_WRITE_NOT_PERMITTED",
    0x1104: "SL_STATUS_BT_ATT_INVALID_PDU",
    0x1105: "SL_STATUS_BT_ATT_INSUFFICIENT_AUTHENTICATION",
    0x1106: "SL_STATUS_BT_ATT_REQUEST_NOT_SUPPORTED",
    0x1107: "SL_STATUS_BT_ATT_INVALID_OFFSET",
    0x1108: "SL_STATUS_BT_ATT_INSUFFICIENT_AUTHORIZATION",
    0x1109: "SL_STATUS_BT_ATT_PREPARE_QUEUE_FULL",
    0x110A: "SL_STATUS_BT_ATT_ATT_NOT_FOUND",
    0x110B: "SL_STATUS_BT_ATT_ATT_NOT_LONG",
    0x110C: "SL_STATUS_BT_ATT_INSUFFICIENT_ENC_KEY_SIZE",
    0x110D: "SL_STATUS_BT_ATT_INVALID_ATT_LENGTH",
    0x110E: "SL_STATUS_BT_ATT_UNLIKELY_ERROR",
    0x110F: "SL_STATUS_BT_ATT_INSUFFICIENT_ENCRYPTION",
    0x1110: "SL_STATUS_BT_ATT_UNSUPPORTED_GROUP_TYPE",
    0x1111: "SL_STATUS_BT_ATT_INSUFFICIENT_RESOURCES",
    0x1112: "SL_STATUS_BT_ATT_OUT_OF_SYNC",
    0x1113: "SL_STATUS_BT_ATT_VALUE_NOT_ALLOWED",
    0x1180: "SL_STATUS_BT_ATT_APPLICATION",
    0x11FC: "SL_STATUS_BT_ATT_WRITE_REQUEST_REJECTED",
    0x11FD: "SL_STATUS_BT_ATT_CLIENT_CHARACTERISTIC_CONFIGURATION_DESCRIPTOR_IMPROPERLY_CONFIGURED",
    0x11FE: "SL_STATUS_BT_ATT_PROCEDURE_ALREADY_IN_PROGRESS",
    0x11FF: "SL_STATUS_BT_ATT_OUT_OF_RANGE",

    # ---------------------------------------------------------------------
    # Bluetooth SMP (Security Manager Protocol) status codes
    # ---------------------------------------------------------------------
    0x1201: "SL_STATUS_BT_SMP_PASSKEY_ENTRY_FAILED",
    0x1202: "SL_STATUS_BT_SMP_OOB_NOT_AVAILABLE",
    0x1203: "SL_STATUS_BT_SMP_AUTHENTICATION_REQUIREMENTS",
    0x1204: "SL_STATUS_BT_SMP_CONFIRM_VALUE_FAILED",
    0x1205: "SL_STATUS_BT_SMP_PAIRING_NOT_SUPPORTED",
    0x1206: "SL_STATUS_BT_SMP_ENCRYPTION_KEY_SIZE",
    0x1207: "SL_STATUS_BT_SMP_COMMAND_NOT_SUPPORTED",
    0x1208: "SL_STATUS_BT_SMP_UNSPECIFIED_REASON",
    0x1209: "SL_STATUS_BT_SMP_REPEATED_ATTEMPTS",
    0x120A: "SL_STATUS_BT_SMP_INVALID_PARAMETERS",
    0x120B: "SL_STATUS_BT_SMP_DHKEY_CHECK_FAILED",
    0x120C: "SL_STATUS_BT_SMP_NUMERIC_COMPARISON_FAILED",
    0x120D: "SL_STATUS_BT_SMP_BREDR_PAIRING_IN_PROGRESS",
    0x120E: "SL_STATUS_BT_SMP_CROSS_TRANSPORT_KEY_DERIVATION_GENERATION_NOT_ALLOWED",
    0x120F: "SL_STATUS_BT_SMP_KEY_REJECTED",

    # ---------------------------------------------------------------------
    # Bluetooth Mesh status codes
    # ---------------------------------------------------------------------
    0x0501: "SL_STATUS_BT_MESH_ALREADY_EXISTS",
    0x0502: "SL_STATUS_BT_MESH_DOES_NOT_EXIST",
    0x0503: "SL_STATUS_BT_MESH_LIMIT_REACHED",
    0x0504: "SL_STATUS_BT_MESH_INVALID_ADDRESS",
    0x0505: "SL_STATUS_BT_MESH_MALFORMED_DATA",
    0x0506: "SL_STATUS_BT_MESH_ALREADY_INITIALIZED",
    0x0507: "SL_STATUS_BT_MESH_NOT_INITIALIZED",
    0x0508: "SL_STATUS_BT_MESH_NO_FRIEND_OFFER",
    0x0509: "SL_STATUS_BT_MESH_PROV_LINK_CLOSED",
    0x050A: "SL_STATUS_BT_MESH_PROV_INVALID_PDU",
    0x050B: "SL_STATUS_BT_MESH_PROV_INVALID_PDU_FORMAT",
    0x050C: "SL_STATUS_BT_MESH_PROV_UNEXPECTED_PDU",
    0x050D: "SL_STATUS_BT_MESH_PROV_CONFIRMATION_FAILED",
    0x050E: "SL_STATUS_BT_MESH_PROV_OUT_OF_RESOURCES",
    0x050F: "SL_STATUS_BT_MESH_PROV_DECRYPTION_FAILED",
    0x0510: "SL_STATUS_BT_MESH_PROV_UNEXPECTED_ERROR",
    0x0511: "SL_STATUS_BT_MESH_PROV_CANNOT_ASSIGN_ADDR",
    0x0512: "SL_STATUS_BT_MESH_ADDRESS_TEMPORARILY_UNAVAILABLE",
    0x0513: "SL_STATUS_BT_MESH_ADDRESS_ALREADY_USED",
    0x0514: "SL_STATUS_BT_MESH_PUBLISH_NOT_CONFIGURED",
    0x0515: "SL_STATUS_BT_MESH_APP_KEY_NOT_BOUND",

    # ---------------------------------------------------------------------
    # Bluetooth Mesh Foundation status codes
    # ---------------------------------------------------------------------
    0x1301: "SL_STATUS_BT_MESH_FOUNDATION_INVALID_ADDRESS",
    0x1302: "SL_STATUS_BT_MESH_FOUNDATION_INVALID_MODEL",
    0x1303: "SL_STATUS_BT_MESH_FOUNDATION_INVALID_APP_KEY",
    0x1304: "SL_STATUS_BT_MESH_FOUNDATION_INVALID_NET_KEY",
    0x1305: "SL_STATUS_BT_MESH_FOUNDATION_INSUFFICIENT_RESOURCES",
    0x1306: "SL_STATUS_BT_MESH_FOUNDATION_KEY_INDEX_EXISTS",
    0x1307: "SL_STATUS_BT_MESH_FOUNDATION_INVALID_PUBLISH_PARAMS",
    0x1308: "SL_STATUS_BT_MESH_FOUNDATION_NOT_SUBSCRIBE_MODEL",
    0x1309: "SL_STATUS_BT_MESH_FOUNDATION_STORAGE_FAILURE",
    0x130A: "SL_STATUS_BT_MESH_FOUNDATION_NOT_SUPPORTED",
    0x130B: "SL_STATUS_BT_MESH_FOUNDATION_CANNOT_UPDATE",
    0x130C: "SL_STATUS_BT_MESH_FOUNDATION_CANNOT_REMOVE",
    0x130D: "SL_STATUS_BT_MESH_FOUNDATION_CANNOT_BIND",
    0x130E: "SL_STATUS_BT_MESH_FOUNDATION_TEMPORARILY_UNABLE",
    0x130F: "SL_STATUS_BT_MESH_FOUNDATION_CANNOT_SET",
    0x1310: "SL_STATUS_BT_MESH_FOUNDATION_UNSPECIFIED",
    0x1311: "SL_STATUS_BT_MESH_FOUNDATION_INVALID_BINDING",

    # ---------------------------------------------------------------------
    # Wi?Fi Errors
    # ---------------------------------------------------------------------
    0x0B01: "SL_STATUS_WIFI_INVALID_KEY",
    0x0B02: "SL_STATUS_WIFI_FIRMWARE_DOWNLOAD_TIMEOUT",
    0x0B03: "SL_STATUS_WIFI_UNSUPPORTED_MESSAGE_ID",
    0x0B04: "SL_STATUS_WIFI_WARNING",
    0x0B05: "SL_STATUS_WIFI_NO_PACKET_TO_RECEIVE",
    0x0B08: "SL_STATUS_WIFI_SLEEP_GRANTED",
    0x0B09: "SL_STATUS_WIFI_SLEEP_NOT_GRANTED",
    0x0B10: "SL_STATUS_WIFI_SECURE_LINK_MAC_KEY_ERROR",
    0x0B11: "SL_STATUS_WIFI_SECURE_LINK_MAC_KEY_ALREADY_BURNED",
    0x0B12: "SL_STATUS_WIFI_SECURE_LINK_RAM_MODE_NOT_ALLOWED",
    0x0B13: "SL_STATUS_WIFI_SECURE_LINK_FAILED_UNKNOWN_MODE",
    0x0B14: "SL_STATUS_WIFI_SECURE_LINK_EXCHANGE_FAILED",
    0x0B18: "SL_STATUS_WIFI_WRONG_STATE",
    0x0B19: "SL_STATUS_WIFI_CHANNEL_NOT_ALLOWED",
    0x0B1A: "SL_STATUS_WIFI_NO_MATCHING_AP",
    0x0B1B: "SL_STATUS_WIFI_CONNECTION_ABORTED",
    0x0B1C: "SL_STATUS_WIFI_CONNECTION_TIMEOUT",
    0x0B1D: "SL_STATUS_WIFI_CONNECTION_REJECTED_BY_AP",
    0x0B1E: "SL_STATUS_WIFI_CONNECTION_AUTH_FAILURE",
    0x0B1F: "SL_STATUS_WIFI_RETRY_EXCEEDED",
    0x0B20: "SL_STATUS_WIFI_TX_LIFETIME_EXCEEDED",

    # ---------------------------------------------------------------------
    # MVP Driver and MVP Math status codes (Compute)
    # ---------------------------------------------------------------------
    0x1501: "SL_STATUS_COMPUTE_DRIVER_FAULT",
    0x1502: "SL_STATUS_COMPUTE_DRIVER_ALU_NAN",
    0x1503: "SL_STATUS_COMPUTE_DRIVER_ALU_OVERFLOW",
    0x1504: "SL_STATUS_COMPUTE_DRIVER_ALU_UNDERFLOW",
    0x1505: "SL_STATUS_COMPUTE_DRIVER_STORE_CONVERSION_OVERFLOW",
    0x1506: "SL_STATUS_COMPUTE_DRIVER_STORE_CONVERSION_UNDERFLOW",
    0x1507: "SL_STATUS_COMPUTE_DRIVER_STORE_CONVERSION_INFINITY",
    0x1508: "SL_STATUS_COMPUTE_DRIVER_STORE_CONVERSION_NAN",
    0x1512: "SL_STATUS_COMPUTE_MATH_NAN",
    0x1513: "SL_STATUS_COMPUTE_MATH_INFINITY",
    0x1514: "SL_STATUS_COMPUTE_MATH_OVERFLOW",
    0x1515: "SL_STATUS_COMPUTE_MATH_UNDERFLOW",
}


def sl_status_to_string(code: int) -> str:
    """
    Convert an sl_status_t value to its SL_STATUS_* name string.
    Returns CODE_UNKNOWN (0x....) for values not defined in sl_status.h.
    """
    name = _STATUS_MAP.get(code)
    if name is not None:
        return name

    # Format unknown codes nicely for 16-bit and 32-bit inputs
    if 0 <= code <= 0xFFFF:
        return f"CODE_UNKNOWN (0x{code:04X})"
    return f"CODE_UNKNOWN (0x{code:08X})"